version: "3.8"

services:
  # frontend:
  #   restart: always
  #   build: ./frontend
  #   ports:
  #     - 3000:3000
  # volumes:
  #   - ./frontend:/app

  backend:
    restart: always
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/blog
    volumes:
      - ./backend:/app
    command: ./docker-entrypoint.sh

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - blog:/data/db

volumes:
  blog:
